version: "3"
services:
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress:ro
      - certbot:/var/www/html:ro
      - ./nginx:/etc/nginx/conf.d:ro
      - ./var/letsencrypt/live/${DOMAIN}:/etc/letsencrypt/live/${DOMAIN}:ro
      - ./var/letsencrypt/archive/${DOMAIN}:/etc/letsencrypt/archive/${DOMAIN}:ro
      - ./var/wp-uploads:/var/www/wp-uploads:ro

  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  php-fpm:
    image: tsertkov/php-fpm-wp:7.2
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - wordpress:/var/www/wordpress:ro
      - ./var/wp-uploads:/var/www/wp-uploads

volumes:
  mysql:
  wordpress:
  certbot:

networks:
  frontend:
  backend:
