version: "3"
services:
  nginx-web:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/nginx/conf.d:/etc/nginx/conf.d
      - ./var/nginx/vhost.d:/etc/nginx/vhost.d
      - ./var/nginx/html:/usr/share/nginx/html
      - ./var/nginx/certs:/etc/nginx/certs:ro
      - ./var/nginx/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: "10"

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ./var/nginx/conf.d:/etc/nginx/conf.d
      - ./var/nginx/vhost.d:/etc/nginx/vhost.d
      - ./var/nginx/html:/usr/share/nginx/html
      - ./var/nginx/certs:/etc/nginx/certs:ro
      - ./var/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: "10"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ./var/nginx/conf.d:/etc/nginx/conf.d
      - ./var/nginx/vhost.d:/etc/nginx/vhost.d
      - ./var/nginx/html:/usr/share/nginx/html
      - ./var/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx-web
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: "10"

  mysql:
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD
  wordpress:
    image: tsertkov/wp-headless:4.9.8
    restart: unless-stopped
    volumes:
      - ./var/wp-core:/var/www/html
      - ./var/wp-content:/var/www/html/wp-content
    environment:
      - VIRTUAL_HOST=${WORDPRESS_DOMAIN}
      - LETSENCRYPT_HOST=${WORDPRESS_DOMAIN}
      - LETSENCRYPT_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_NAME
      - DBI_AWS_ACCESS_KEY_ID
      - DBI_AWS_SECRET_ACCESS_KEY
      - WORDPRESS_URL
      - WORDPRESS_TITLE
      - WORDPRESS_ADMIN_EMAIL
      - FORCE_SSL_ADMIN
volumes:
  mysql:
